### ISSUE TITLE
integrations?

### ISSUE THREAD

**Issue by pokeball99** [phillipadsmith/awesome-github#18]
i know that github is now doing this already via https://github.com/integrations, but that is really taking days and weeks for a new service to show up on their,things such like gitcop.com and such are still not there
(plus it would also just complete this awesome list more :) )

**Comment by phillipadsmith** [comment]
> i know that github is now doing this already via https://github.com/integrations, but that is really taking days and weeks for a new service to show up on their,things such like gitcop.com and such are still not there

@pokeball99  Good idea. Care to make a pull request with those additions?

**Comment by pokeball99** [comment]
Sure @phillipadsmith, I'll do that sometime today when I get the time
