### ISSUE TITLE
Merging with other english main repo

### ISSUE THREAD

**Issue by fkromer** [phillipadsmith/awesome-github#29]
What about merging with the [english "awesome-github" repo with the most stars](https://github.com/Kikobeats/awesome-github)?

**Comment by phillipadsmith** [comment]
Howdy @fkromer,

Happy to consider that if @Kikobeats thinks it's a sensible merge.

Phillip.

**Comment by Kikobeats** [comment]
For me it's OK!

I started my list as personal selection of things that I like or I use.

**Comment by fkromer** [comment]
Great, I wait with adding my items till you merged your lists...

**Comment by koppor** [comment]
May I ask about the progress? This repo also gets more and more popular. E.g., it is linked from https://github.com/dictcp/awesome-git/pull/30 (which in turn is linked from https://github.com/sindresorhus/awesome/pull/1329).

**Comment by phillipadsmith** [comment]
Thanks for the ping @koppor.

I've had another looks at @Kikobeats' list and I believe that there's enough of a difference in purpose that I'm going to keep this list separate.

My intention was to catalogue what is awesome about GitHub as a place to co-create, and I'm happy to continue doing that here.

Thanks for all of your input, including @fkromer 

Best,

Phillip.
