### ISSUE TITLE
cli-github

### ISSUE THREAD

**Issue by harshasrinivas** [phillipadsmith/awesome-github#7]
My command line app for github - [Link to the repo](https://github.com/harshasrinivas/cli-github).
I feel that this should make it to the list.
Tell me what you feel, and if it's okay, i'll send you a PR.

And awesome work btw! :smile:

**Comment by phillipadsmith** [comment]
@harshasrinivas Did you add it to the GitHub cheat sheet list? Feel free to send a PR to this repo too.

**Comment by harshasrinivas** [comment]
Sure, will add it to the cheat sheet list too.
PR sent @phillipadsmith
